//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collaboration.Web.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Collaboration.Web.UI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD Request sent three times.
        /// </summary>
        public static string CADThreeRequestsIsue {
            get {
                return ResourceManager.GetString("CADThreeRequestsIsue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5,10,15,20.
        /// </summary>
        public static string ChartDataOrdersDeadline {
            get {
                return ResourceManager.GetString("ChartDataOrdersDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string DB_AdminRoleID {
            get {
                return ResourceManager.GetString("DB_AdminRoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string DB_BanglesID {
            get {
                return ResourceManager.GetString("DB_BanglesID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string DB_BraceletID {
            get {
                return ResourceManager.GetString("DB_BraceletID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string DB_ChainID {
            get {
                return ResourceManager.GetString("DB_ChainID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string DB_EarringsID {
            get {
                return ResourceManager.GetString("DB_EarringsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string DB_FactoryRoleID {
            get {
                return ResourceManager.GetString("DB_FactoryRoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string DB_IsMatchingETID {
            get {
                return ResourceManager.GetString("DB_IsMatchingETID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string DB_JacketsID {
            get {
                return ResourceManager.GetString("DB_JacketsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string DB_NecklaceID {
            get {
                return ResourceManager.GetString("DB_NecklaceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string DB_NSMID {
            get {
                return ResourceManager.GetString("DB_NSMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string DB_PedantID {
            get {
                return ResourceManager.GetString("DB_PedantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string DB_RingID {
            get {
                return ResourceManager.GetString("DB_RingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string DB_RingMountID {
            get {
                return ResourceManager.GetString("DB_RingMountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM.
        /// </summary>
        public static string DB_SampleSerialNumberPrefix {
            get {
                return ResourceManager.GetString("DB_SampleSerialNumberPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string DB_SampleStatus_Pending {
            get {
                return ResourceManager.GetString("DB_SampleStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string DB_SampleStatus_ReceivedAtChina {
            get {
                return ResourceManager.GetString("DB_SampleStatus_ReceivedAtChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string DB_SampleStatus_ReceivedAtUK {
            get {
                return ResourceManager.GetString("DB_SampleStatus_ReceivedAtUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string DB_SampleStatus_ReturnedToUK {
            get {
                return ResourceManager.GetString("DB_SampleStatus_ReturnedToUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string DB_SampleStatus_SentToChina {
            get {
                return ResourceManager.GetString("DB_SampleStatus_SentToChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        public static string DB_SerialNumberPrefix {
            get {
                return ResourceManager.GetString("DB_SerialNumberPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string DB_Status_CADConfirmed {
            get {
                return ResourceManager.GetString("DB_Status_CADConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string DB_Status_CADInProgress {
            get {
                return ResourceManager.GetString("DB_Status_CADInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string DB_Status_ChangeRequest {
            get {
                return ResourceManager.GetString("DB_Status_ChangeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string DB_Status_Delayed {
            get {
                return ResourceManager.GetString("DB_Status_Delayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string DB_Status_Initiated {
            get {
                return ResourceManager.GetString("DB_Status_Initiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string DB_Status_PendingCustomerConfirmation {
            get {
                return ResourceManager.GetString("DB_Status_PendingCustomerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string DB_Status_PendingTMReview {
            get {
                return ResourceManager.GetString("DB_Status_PendingTMReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string DB_Status_ProductionInProgress {
            get {
                return ResourceManager.GetString("DB_Status_ProductionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string DB_Status_PrototypingBegins {
            get {
                return ResourceManager.GetString("DB_Status_PrototypingBegins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string DB_Status_Shipped {
            get {
                return ResourceManager.GetString("DB_Status_Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string DB_SubTypeFinishedID {
            get {
                return ResourceManager.GetString("DB_SubTypeFinishedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string DB_SubTypeMountID {
            get {
                return ResourceManager.GetString("DB_SubTypeMountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string DB_TMRoleID {
            get {
                return ResourceManager.GetString("DB_TMRoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E92E9036-B16B-477C-8DA9-E4C134EC9B15.
        /// </summary>
        public static string EncryptPassphrase {
            get {
                return ResourceManager.GetString("EncryptPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured. Please contact Administrator for details.
        /// </summary>
        public static string Err_General {
            get {
                return ResourceManager.GetString("Err_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UserName or Password.
        /// </summary>
        public static string Err_InvalidCredentials {
            get {
                return ResourceManager.GetString("Err_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid E-mail Address.
        /// </summary>
        public static string Err_InvalidEmail {
            get {
                return ResourceManager.GetString("Err_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Image file.
        /// </summary>
        public static string Err_InvalidImage {
            get {
                return ResourceManager.GetString("Err_InvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string Err_InvalidPassword {
            get {
                return ResourceManager.GetString("Err_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UserName.
        /// </summary>
        public static string Err_InvalidUserName {
            get {
                return ResourceManager.GetString("Err_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is required.
        /// </summary>
        public static string Err_ReqUserName {
            get {
                return ResourceManager.GetString("Err_ReqUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is reuired.
        /// </summary>
        public static string Err_ReqUserPassword {
            get {
                return ResourceManager.GetString("Err_ReqUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already taken..
        /// </summary>
        public static string Err_UniqUsername {
            get {
                return ResourceManager.GetString("Err_UniqUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload the file to import.
        /// </summary>
        public static string ErrRequiredUploadFile {
            get {
                return ResourceManager.GetString("ErrRequiredUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload the CAD.
        /// </summary>
        public static string ErrUploadCAD {
            get {
                return ResourceManager.GetString("ErrUploadCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM yyyy.
        /// </summary>
        public static string FormatDate {
            get {
                return ResourceManager.GetString("FormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd MMM yyyy}.
        /// </summary>
        public static string FormatDateForBinders {
            get {
                return ResourceManager.GetString("FormatDateForBinders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM yyyy HH:mm.
        /// </summary>
        public static string FormatDateTime {
            get {
                return ResourceManager.GetString("FormatDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd MMM yyyy HH:mm}.
        /// </summary>
        public static string FormatDateTimeForBinders {
            get {
                return ResourceManager.GetString("FormatDateTimeForBinders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d M Y.
        /// </summary>
        public static string FormatDateUI {
            get {
                return ResourceManager.GetString("FormatDateUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been added successfully.
        /// </summary>
        public static string Info_Added {
            get {
                return ResourceManager.GetString("Info_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order has been placed successfully.
        /// </summary>
        public static string Info_CADAdded {
            get {
                return ResourceManager.GetString("Info_CADAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order has been updated successfully.
        /// </summary>
        public static string Info_CADUpdated {
            get {
                return ResourceManager.GetString("Info_CADUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully.
        /// </summary>
        public static string Info_Deleted {
            get {
                return ResourceManager.GetString("Info_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you are logging for the first time, Please change your Password..
        /// </summary>
        public static string Info_ForcePasswordChanged {
            get {
                return ResourceManager.GetString("Info_ForcePasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully.
        /// </summary>
        public static string Info_PasswordChanged {
            get {
                return ResourceManager.GetString("Info_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset, Please check your registered Email for Information.
        /// </summary>
        public static string Info_PasswordReeset {
            get {
                return ResourceManager.GetString("Info_PasswordReeset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks, Your response has been sent..
        /// </summary>
        public static string Info_ResponseSent {
            get {
                return ResourceManager.GetString("Info_ResponseSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated successfully.
        /// </summary>
        public static string Info_Updated {
            get {
                return ResourceManager.GetString("Info_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} records processed successfully.
        /// </summary>
        public static string InfoRecordsProcessed {
            get {
                return ResourceManager.GetString("InfoRecordsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your response has already been registered..
        /// </summary>
        public static string InfoResponseRegistered {
            get {
                return ResourceManager.GetString("InfoResponseRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string MaxSpecimenUpload {
            get {
                return ResourceManager.GetString("MaxSpecimenUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Mounts - Review CAD.
        /// </summary>
        public static string SubjectCADConfirmation {
            get {
                return ResourceManager.GetString("SubjectCADConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Mounts - CAD Response.
        /// </summary>
        public static string SubjectCADResponse {
            get {
                return ResourceManager.GetString("SubjectCADResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Mounts - Password Reset.
        /// </summary>
        public static string SubjectResetPassword {
            get {
                return ResourceManager.GetString("SubjectResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to River Mounts.
        /// </summary>
        public static string SubjectUserRegistration {
            get {
                return ResourceManager.GetString("SubjectUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved.
        /// </summary>
        public static string TextForCurve {
            get {
                return ResourceManager.GetString("TextForCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve with a Kink.
        /// </summary>
        public static string TextForKink {
            get {
                return ResourceManager.GetString("TextForKink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight.
        /// </summary>
        public static string TextForStraight {
            get {
                return ResourceManager.GetString("TextForStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Symmetrical Curve.
        /// </summary>
        public static string TextForSymmetrical {
            get {
                return ResourceManager.GetString("TextForSymmetrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        public static string UI_Active {
            get {
                return ResourceManager.GetString("UI_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn btn-danger.
        /// </summary>
        public static string UI_BtnDanger {
            get {
                return ResourceManager.GetString("UI_BtnDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn btn-default.
        /// </summary>
        public static string UI_BtnDefault {
            get {
                return ResourceManager.GetString("UI_BtnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn btn-primary.
        /// </summary>
        public static string UI_BtnPrimary {
            get {
                return ResourceManager.GetString("UI_BtnPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn btn-success.
        /// </summary>
        public static string UI_BtnSuccess {
            get {
                return ResourceManager.GetString("UI_BtnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-block alert-danger fade in.
        /// </summary>
        public static string UI_FaillureMessageClass {
            get {
                return ResourceManager.GetString("UI_FaillureMessageClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-success alert-block fade in.
        /// </summary>
        public static string UI_SuccessMessageClass {
            get {
                return ResourceManager.GetString("UI_SuccessMessageClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-warning fade in.
        /// </summary>
        public static string UI_WarningMessageClass {
            get {
                return ResourceManager.GetString("UI_WarningMessageClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string Val_ApproachingDeadline {
            get {
                return ResourceManager.GetString("Val_ApproachingDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.xls&quot;.
        /// </summary>
        public static string ValidCustomerImportExtensions {
            get {
                return ResourceManager.GetString("ValidCustomerImportExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5242880.
        /// </summary>
        public static string ValidImageFileSize {
            get {
                return ResourceManager.GetString("ValidImageFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.bmp&quot;,&quot;.jpeg&quot;,&quot;.jpg&quot;,&quot;.png&quot;.
        /// </summary>
        public static string ValidProfileImageExtensions {
            get {
                return ResourceManager.GetString("ValidProfileImageExtensions", resourceCulture);
            }
        }
    }
}
