#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collaboration.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_83425_rivermount")]
	public partial class CollaborationLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CollaborationLinqDataContext() : 
				base(global::Collaboration.Data.Properties.Settings.Default.DB_83425_rivermountConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CollaborationLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CollaborationLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CollaborationLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CollaborationLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Order_Delete")]
		public ISingleResult<Order_DeleteResult> Order_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID);
			return ((ISingleResult<Order_DeleteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Order_Update")]
		public int Order_Update(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpectedShippingDate", DbType="DateTime")] System.Nullable<System.DateTime> expectedShippingDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModelTypeID", DbType="Int")] System.Nullable<int> modelTypeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModelSubTypeID", DbType="Int")] System.Nullable<int> modelSubTypeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModelNumber", DbType="VarChar(50)")] string modelNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProcessTypeID", DbType="Int")] System.Nullable<int> processTypeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MetalID", DbType="Int")] System.Nullable<int> metalID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MetalOther", DbType="VarChar(50)")] string metalOther, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FingerSizeID", DbType="Int")] System.Nullable<int> fingerSizeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FingerSizeOther", DbType="VarChar(10)")] string fingerSizeOther, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantity", DbType="VarChar(2)")] string quantity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuantityOther", DbType="VarChar(3)")] string quantityOther, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Length", DbType="Decimal(4,2)")] System.Nullable<decimal> length, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LengthMeasurement", DbType="VarChar(10)")] string lengthMeasurement, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PriorityID", DbType="Int")] System.Nullable<int> priorityID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MakeExactCopies", DbType="Bit")] System.Nullable<bool> makeExactCopies, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RingTypeID", DbType="Int")] System.Nullable<int> ringTypeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsExistingModel", DbType="Bit")] System.Nullable<bool> isExistingModel, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModelToMatch", DbType="VarChar(50)")] string modelToMatch, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CurveType", DbType="VarChar(50)")] string curveType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TailoredType", DbType="VarChar(50)")] string tailoredType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsFinishAtSomePoint", DbType="Bit")] System.Nullable<bool> isFinishAtSomePoint, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdditionalInfo", DbType="NVarChar(MAX)")] string additionalInfo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPF", DbType="Bit")] System.Nullable<bool> isPF, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HeadSize", DbType="VarChar(10)")] string headSize, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsCADRequested", DbType="Bit")] System.Nullable<bool> isCADRequested, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSampleProvided", DbType="Bit")] System.Nullable<bool> isSampleProvided, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoOfSamples", DbType="TinyInt")] System.Nullable<byte> noOfSamples, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MakeExactCopiesSample", DbType="Bit")] System.Nullable<bool> makeExactCopiesSample, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsStoneProvided", DbType="Bit")] System.Nullable<bool> isStoneProvided, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StoneDescription", DbType="NVarChar(MAX)")] string stoneDescription, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SettingInstructions", DbType="NVarChar(MAX)")] string settingInstructions, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remarks", DbType="NVarChar(MAX)")] string remarks, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TMUserID", DbType="Int")] System.Nullable<int> tMUserID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderStatusID", DbType="Int")] System.Nullable<int> orderStatusID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AssignedTo", DbType="Int")] System.Nullable<int> assignedTo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID, customerID, expectedShippingDate, modelTypeID, modelSubTypeID, modelNumber, processTypeID, metalID, metalOther, fingerSizeID, fingerSizeOther, quantity, quantityOther, length, lengthMeasurement, priorityID, makeExactCopies, ringTypeID, isExistingModel, modelToMatch, curveType, tailoredType, isFinishAtSomePoint, additionalInfo, isPF, headSize, isCADRequested, isSampleProvided, noOfSamples, makeExactCopiesSample, isStoneProvided, stoneDescription, settingInstructions, remarks, tMUserID, orderStatusID, assignedTo);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class Order_DeleteResult
	{
		
		private System.Nullable<bool> _Column1;
		
		public Order_DeleteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Bit")]
		public System.Nullable<bool> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
