<?xml version="1.0" encoding="utf-8"?><Database Name="DB_83425_rivermount" Class="CollaborationLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=s11.winhost.com;Initial Catalog=DB_83425_rivermount;Persist Security Info=True;User ID=DB_83425_rivermount_user;MultipleActiveResultSets=True" SettingsObjectName="Collaboration.Data.Properties.Settings" SettingsPropertyName="DB_83425_rivermountConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.Order_Delete" Method="Order_Delete">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Order_DeleteResult">
      <Column Name="" Member="Column1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Order_Update" Method="Order_Update">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ExpectedShippingDate" Parameter="expectedShippingDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ModelTypeID" Parameter="modelTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ModelSubTypeID" Parameter="modelSubTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ModelNumber" Parameter="modelNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProcessTypeID" Parameter="processTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MetalID" Parameter="metalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MetalOther" Parameter="metalOther" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FingerSizeID" Parameter="fingerSizeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FingerSizeOther" Parameter="fingerSizeOther" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="QuantityOther" Parameter="quantityOther" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="Length" Parameter="length" Type="System.Decimal" DbType="Decimal(4,2)" />
    <Parameter Name="LengthMeasurement" Parameter="lengthMeasurement" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="PriorityID" Parameter="priorityID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MakeExactCopies" Parameter="makeExactCopies" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="RingTypeID" Parameter="ringTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsExistingModel" Parameter="isExistingModel" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ModelToMatch" Parameter="modelToMatch" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CurveType" Parameter="curveType" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TailoredType" Parameter="tailoredType" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IsFinishAtSomePoint" Parameter="isFinishAtSomePoint" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AdditionalInfo" Parameter="additionalInfo" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="IsPF" Parameter="isPF" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="HeadSize" Parameter="headSize" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="IsCADRequested" Parameter="isCADRequested" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsSampleProvided" Parameter="isSampleProvided" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NoOfSamples" Parameter="noOfSamples" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="MakeExactCopiesSample" Parameter="makeExactCopiesSample" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsStoneProvided" Parameter="isStoneProvided" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="StoneDescription" Parameter="stoneDescription" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="SettingInstructions" Parameter="settingInstructions" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Remarks" Parameter="remarks" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="TMUserID" Parameter="tMUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="OrderStatusID" Parameter="orderStatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AssignedTo" Parameter="assignedTo" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>