//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collaboration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageThread
    {
        public MessageThread()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int MessageThreadID { get; set; }
        public int OrderID { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Status { get; set; }
        public string ClosingRemarks { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Order Order { get; set; }
    }
}
