//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collaboration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.MessageThreads = new HashSet<MessageThread>();
            this.OrderParticipants = new HashSet<OrderParticipant>();
            this.OrdersCADs = new HashSet<OrdersCAD>();
            this.Specimens = new HashSet<Specimen>();
        }
    
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int ModelTypeID { get; set; }
        public Nullable<int> ModelSubTypeID { get; set; }
        public string ModelNumber { get; set; }
        public string SerialNumber { get; set; }
        public int ProcessTypeID { get; set; }
        public Nullable<int> MetalID { get; set; }
        public string MetalOther { get; set; }
        public Nullable<int> FingerSizeID { get; set; }
        public string FingerSizeOther { get; set; }
        public string Quantity { get; set; }
        public string QuantityOther { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string LengthMeasurement { get; set; }
        public short PriorityID { get; set; }
        public Nullable<bool> MakeExactCopies { get; set; }
        public Nullable<short> RingTypeID { get; set; }
        public Nullable<bool> IsExistingModel { get; set; }
        public string ModelToMatch { get; set; }
        public string CurveType { get; set; }
        public string TailoredType { get; set; }
        public Nullable<bool> IsFinishAtSomePoint { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<bool> IsPF { get; set; }
        public string HeadSize { get; set; }
        public Nullable<bool> IsCADRequested { get; set; }
        public Nullable<bool> IsSampleProvided { get; set; }
        public Nullable<byte> NoOfSamples { get; set; }
        public Nullable<bool> MakeExactCopiesSample { get; set; }
        public Nullable<bool> IsStoneProvided { get; set; }
        public string StoneDescription { get; set; }
        public string SettingInstructions { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TMUserID { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public int OrderStatusID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> ExpectedShippingDate { get; set; }
    
        public virtual FingerSize FingerSize { get; set; }
        public virtual ICollection<MessageThread> MessageThreads { get; set; }
        public virtual Metal Metal { get; set; }
        public virtual ICollection<OrderParticipant> OrderParticipants { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual ProcessType ProcessType { get; set; }
        public virtual RingType RingType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrdersCAD> OrdersCADs { get; set; }
        public virtual ICollection<Specimen> Specimens { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ModelType ModelType { get; set; }
    }
}
