//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collaboration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public Sample()
        {
            this.SamplesTrackings = new HashSet<SamplesTracking>();
        }
    
        public int SampleID { get; set; }
        public int OrderID { get; set; }
        public string SampleSerialNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsReturned { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<SamplesTracking> SamplesTrackings { get; set; }
    }
}
