//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collaboration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specimen
    {
        public int SpecimenID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public string ImageLocationURL { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual Order Order { get; set; }
    }
}
