//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collaboration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.TicketsAttachments = new HashSet<TicketsAttachment>();
            this.TicketToes = new HashSet<TicketTo>();
        }
    
        public int TicketThreadID { get; set; }
        public int TicketID { get; set; }
        public string TicketText { get; set; }
        public int AssignedFrom { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> HasAttachment { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual TicketThread TicketThread { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TicketsAttachment> TicketsAttachments { get; set; }
        public virtual ICollection<TicketTo> TicketToes { get; set; }
    }
}
