//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collaboration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Messages = new HashSet<Message>();
            this.MessageThreads = new HashSet<MessageThread>();
            this.MessageThreads1 = new HashSet<MessageThread>();
            this.MessageToes = new HashSet<MessageTo>();
            this.OrderParticipants = new HashSet<OrderParticipant>();
            this.OrdersCADs = new HashSet<OrdersCAD>();
            this.Orders = new HashSet<Order>();
            this.TicketThreads = new HashSet<TicketThread>();
            this.TicketThreads1 = new HashSet<TicketThread>();
            this.TicketThreads1_1 = new HashSet<TicketThread>();
            this.Tickets = new HashSet<Ticket>();
            this.TicketToes = new HashSet<TicketTo>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] Password { get; set; }
        public string EMail { get; set; }
        public string Mobile { get; set; }
        public string ImageLocationURL { get; set; }
        public bool IsActive { get; set; }
        public int RoleID { get; set; }
        public bool DefaultPasswordChanged { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<MessageThread> MessageThreads { get; set; }
        public virtual ICollection<MessageThread> MessageThreads1 { get; set; }
        public virtual ICollection<MessageTo> MessageToes { get; set; }
        public virtual ICollection<OrderParticipant> OrderParticipants { get; set; }
        public virtual ICollection<OrdersCAD> OrdersCADs { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<TicketThread> TicketThreads { get; set; }
        public virtual ICollection<TicketThread> TicketThreads1 { get; set; }
        public virtual ICollection<TicketThread> TicketThreads1_1 { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<TicketTo> TicketToes { get; set; }
    }
}
