//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Collaboration.Business.Entities
{
    public partial class MessagesAttachment
    {
        #region Primitive Properties
    
        public virtual int AttachmentID
        {
            get;
            set;
        }
    
        public virtual int MessageID
        {
            get { return _messageID; }
            set
            {
                if (_messageID != value)
                {
                    if (Message != null && Message.MessageID != value)
                    {
                        Message = null;
                    }
                    _messageID = value;
                }
            }
        }
        private int _messageID;
    
        public virtual string LocationURL
        {
            get;
            set;
        }
    
        public virtual string ContentType
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsActive
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Message Message
        {
            get { return _message; }
            set
            {
                if (!ReferenceEquals(_message, value))
                {
                    var previousValue = _message;
                    _message = value;
                    FixupMessage(previousValue);
                }
            }
        }
        private Message _message;

        #endregion
        #region Association Fixup
    
        private void FixupMessage(Message previousValue)
        {
            if (previousValue != null && previousValue.MessagesAttachments.Contains(this))
            {
                previousValue.MessagesAttachments.Remove(this);
            }
    
            if (Message != null)
            {
                if (!Message.MessagesAttachments.Contains(this))
                {
                    Message.MessagesAttachments.Add(this);
                }
                if (MessageID != Message.MessageID)
                {
                    MessageID = Message.MessageID;
                }
            }
        }

        #endregion
    }
}
