//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Collaboration.Business.Entities
{
    public partial class MessageThread
    {
        #region Primitive Properties
    
        public virtual int MessageThreadID
        {
            get;
            set;
        }
    
        public virtual int OrderID
        {
            get { return _orderID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_orderID != value)
                    {
                        if (Order != null && Order.OrderID != value)
                        {
                            Order = null;
                        }
                        _orderID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _orderID;
    
        public virtual string Subject
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Status
        {
            get;
            set;
        }
    
        public virtual string ClosingRemarks
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LastModifiedBy
        {
            get { return _lastModifiedBy; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_lastModifiedBy != value)
                    {
                        if (User != null && User.UserID != value)
                        {
                            User = null;
                        }
                        _lastModifiedBy = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _lastModifiedBy;
    
        public virtual Nullable<int> AssignedTo
        {
            get { return _assignedTo; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_assignedTo != value)
                    {
                        if (User1 != null && User1.UserID != value)
                        {
                            User1 = null;
                        }
                        _assignedTo = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _assignedTo;
    
        public virtual Nullable<bool> IsActive
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Message> Messages
        {
            get
            {
                if (_messages == null)
                {
                    var newCollection = new FixupCollection<Message>();
                    newCollection.CollectionChanged += FixupMessages;
                    _messages = newCollection;
                }
                return _messages;
            }
            set
            {
                if (!ReferenceEquals(_messages, value))
                {
                    var previousValue = _messages as FixupCollection<Message>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMessages;
                    }
                    _messages = value;
                    var newValue = value as FixupCollection<Message>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMessages;
                    }
                }
            }
        }
        private ICollection<Message> _messages;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;
    
        public virtual User User1
        {
            get { return _user1; }
            set
            {
                if (!ReferenceEquals(_user1, value))
                {
                    var previousValue = _user1;
                    _user1 = value;
                    FixupUser1(previousValue);
                }
            }
        }
        private User _user1;
    
        public virtual Order Order
        {
            get { return _order; }
            set
            {
                if (!ReferenceEquals(_order, value))
                {
                    var previousValue = _order;
                    _order = value;
                    FixupOrder(previousValue);
                }
            }
        }
        private Order _order;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.MessageThreads.Contains(this))
            {
                previousValue.MessageThreads.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.MessageThreads.Contains(this))
                {
                    User.MessageThreads.Add(this);
                }
                if (LastModifiedBy != User.UserID)
                {
                    LastModifiedBy = User.UserID;
                }
            }
            else if (!_settingFK)
            {
                LastModifiedBy = null;
            }
        }
    
        private void FixupUser1(User previousValue)
        {
            if (previousValue != null && previousValue.MessageThreads1.Contains(this))
            {
                previousValue.MessageThreads1.Remove(this);
            }
    
            if (User1 != null)
            {
                if (!User1.MessageThreads1.Contains(this))
                {
                    User1.MessageThreads1.Add(this);
                }
                if (AssignedTo != User1.UserID)
                {
                    AssignedTo = User1.UserID;
                }
            }
            else if (!_settingFK)
            {
                AssignedTo = null;
            }
        }
    
        private void FixupOrder(Order previousValue)
        {
            if (previousValue != null && previousValue.MessageThreads.Contains(this))
            {
                previousValue.MessageThreads.Remove(this);
            }
    
            if (Order != null)
            {
                if (!Order.MessageThreads.Contains(this))
                {
                    Order.MessageThreads.Add(this);
                }
                if (OrderID != Order.OrderID)
                {
                    OrderID = Order.OrderID;
                }
            }
        }
    
        private void FixupMessages(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Message item in e.NewItems)
                {
                    item.MessageThread = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Message item in e.OldItems)
                {
                    if (ReferenceEquals(item.MessageThread, this))
                    {
                        item.MessageThread = null;
                    }
                }
            }
        }

        #endregion
    }
}
