//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Collaboration.Business.Entities
{
    public partial class OrderParticipant
    {
        #region Primitive Properties
    
        public virtual int OrderParticipantID
        {
            get;
            set;
        }
    
        public virtual int OrderID
        {
            get { return _orderID; }
            set
            {
                if (_orderID != value)
                {
                    if (Order != null && Order.OrderID != value)
                    {
                        Order = null;
                    }
                    _orderID = value;
                }
            }
        }
        private int _orderID;
    
        public virtual int UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (User != null && User.UserID != value)
                    {
                        User = null;
                    }
                    _userID = value;
                }
            }
        }
        private int _userID;
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;
    
        public virtual Order Order
        {
            get { return _order; }
            set
            {
                if (!ReferenceEquals(_order, value))
                {
                    var previousValue = _order;
                    _order = value;
                    FixupOrder(previousValue);
                }
            }
        }
        private Order _order;

        #endregion
        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.OrderParticipants.Contains(this))
            {
                previousValue.OrderParticipants.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.OrderParticipants.Contains(this))
                {
                    User.OrderParticipants.Add(this);
                }
                if (UserID != User.UserID)
                {
                    UserID = User.UserID;
                }
            }
        }
    
        private void FixupOrder(Order previousValue)
        {
            if (previousValue != null && previousValue.OrderParticipants.Contains(this))
            {
                previousValue.OrderParticipants.Remove(this);
            }
    
            if (Order != null)
            {
                if (!Order.OrderParticipants.Contains(this))
                {
                    Order.OrderParticipants.Add(this);
                }
                if (OrderID != Order.OrderID)
                {
                    OrderID = Order.OrderID;
                }
            }
        }

        #endregion
    }
}
