//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Collaboration.Business.Entities
{
    public partial class SamplesTracking
    {
        #region Primitive Properties

        public virtual int SampleTrackID
        {
            get;
            set;
        }
        public virtual Nullable<int> Updatedby
        {
            get;
            set;
        }
        public virtual int SampleID
        {
            get { return _sampleID; }
            set
            {
                if (_sampleID != value)
                {
                    if (Sample != null && Sample.SampleID != value)
                    {
                        Sample = null;
                    }
                    _sampleID = value;
                }
            }
        }
        private int _sampleID;

        public virtual int SampleStatusID
        {
            get { return _sampleStatusID; }
            set
            {
                if (_sampleStatusID != value)
                {
                    if (SampleStatu != null && SampleStatu.SampleStatusID != value)
                    {
                        SampleStatu = null;
                    }
                    _sampleStatusID = value;
                }
            }
        }
        private int _sampleStatusID;

        public virtual Nullable<bool> IsActive
        {
            get;
            set;
        }

        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }

        public virtual Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties

        public virtual Sample Sample
        {
            get { return _sample; }
            set
            {
                if (!ReferenceEquals(_sample, value))
                {
                    var previousValue = _sample;
                    _sample = value;
                    FixupSample(previousValue);
                }
            }
        }
        private Sample _sample;

        public virtual SampleStatu SampleStatu
        {
            get { return _sampleStatu; }
            set
            {
                if (!ReferenceEquals(_sampleStatu, value))
                {
                    var previousValue = _sampleStatu;
                    _sampleStatu = value;
                    FixupSampleStatu(previousValue);
                }
            }
        }
        private SampleStatu _sampleStatu;

        #endregion

        #region Association Fixup

        private void FixupSample(Sample previousValue)
        {
            if (previousValue != null && previousValue.SamplesTrackings.Contains(this))
            {
                previousValue.SamplesTrackings.Remove(this);
            }

            if (Sample != null)
            {
                if (!Sample.SamplesTrackings.Contains(this))
                {
                    Sample.SamplesTrackings.Add(this);
                }
                if (SampleID != Sample.SampleID)
                {
                    SampleID = Sample.SampleID;
                }
            }
        }

        private void FixupSampleStatu(SampleStatu previousValue)
        {
            if (previousValue != null && previousValue.SamplesTrackings.Contains(this))
            {
                previousValue.SamplesTrackings.Remove(this);
            }

            if (SampleStatu != null)
            {
                if (!SampleStatu.SamplesTrackings.Contains(this))
                {
                    SampleStatu.SamplesTrackings.Add(this);
                }
                if (SampleStatusID != SampleStatu.SampleStatusID)
                {
                    SampleStatusID = SampleStatu.SampleStatusID;
                }
            }
        }

        #endregion

    }
}
