//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Collaboration.Business.Entities
{
    public partial class TicketsAttachment
    {
        #region Primitive Properties
    
        public virtual int AttachmentID
        {
            get;
            set;
        }
    
        public virtual int TicketID
        {
            get { return _ticketID; }
            set
            {
                if (_ticketID != value)
                {
                    if (Ticket != null && Ticket.TicketID != value)
                    {
                        Ticket = null;
                    }
                    _ticketID = value;
                }
            }
        }
        private int _ticketID;
    
        public virtual string LocationURL
        {
            get;
            set;
        }
    
        public virtual string ContentType
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsActive
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ModifyDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Ticket Ticket
        {
            get { return _ticket; }
            set
            {
                if (!ReferenceEquals(_ticket, value))
                {
                    var previousValue = _ticket;
                    _ticket = value;
                    FixupTicket(previousValue);
                }
            }
        }
        private Ticket _ticket;

        #endregion
        #region Association Fixup
    
        private void FixupTicket(Ticket previousValue)
        {
            if (previousValue != null && previousValue.TicketsAttachments.Contains(this))
            {
                previousValue.TicketsAttachments.Remove(this);
            }
    
            if (Ticket != null)
            {
                if (!Ticket.TicketsAttachments.Contains(this))
                {
                    Ticket.TicketsAttachments.Add(this);
                }
                if (TicketID != Ticket.TicketID)
                {
                    TicketID = Ticket.TicketID;
                }
            }
        }

        #endregion
    }
}
